# Generated by Django 4.1.7 on 2024-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=128)),
                ("logo", models.ImageField(blank=True, upload_to="compnay/logo")),
                ("location", models.CharField(max_length=150)),
            ],
        ),
    ]
